image: python:alpine3.7

stages:
  - unit-test
  - lint
  - build-push
  - update-service

unit-tests:
  stage: unit-test
  tags:
    - sample-app
  script:
    - pip3 install coverage nose nose-exclude rednose
    - pip3 install -r requirements.txt
    - nosetests . -v
  only:
    refs:
      - /.*/
  except:
    changes:
      - README.md
      - .gitignore

codestyle-check:
  stage: lint
  tags:
    - sample-app
  script:
    - pip3 install pylint
    - pip3 install -r requirements.txt
    - pylint src -v
  only:
    refs:
      - /.*/
  except:
    changes:
      - README.md
      - .gitignore

build-push-image:
  stage: build-push
  tags:
    - sample-app
  script:
    - echo 'Build and push docker images'
    - docker build -t $DOCKER_REPO/sample-app:latest .
    - docker push $DOCKER_REPO/sample-app:latest
  only:
    refs:
      - master
  except:
    changes:
      - README.md
      - .gitignore

update-gke-service:
  stage: update-service
  script:
    - echo 'Update GKE Service'
    - export PROJECT_ID=learning-245417
    - export PROJECT_NUMBER=$(gcloud projects describe ${PROJECT_ID} --format="value(projectNumber)")
    - export CLUSTER_NAME=anthos-cluster-417
    - export CLUSTER_REGION=us-central1
    - export CLUSTER_LOCATION=${CLUSTER_REGION}-a
    - export WORKLOAD_POOL=${PROJECT_ID}.svc.id.goog
    - export MESH_ID="proj-${PROJECT_NUMBER}"
    - export CHANNEL=regular
    - export SERVICE_ACCOUNT_NAME=${CLUSTER_NAME}-sa
    - gcloud config set project ${PROJECT_ID}
    - gcloud config set compute/zone ${CLUSTER_LOCATION}
    - gcloud container clusters get-credentials anthos-cluster-417
    - kubectl apply -f deployment.yaml
  only:
    refs:
      - master
  except:
    changes:
      - README.md
      - .gitignore
